name: datalad_binder

channels:
  - default
  - conda-forge

dependencies:
  - python=3.10.*
  - pip
  - datalad=0.19.*
  - pip:
      - nbgitpuller
      - bash_kernel
      - jupyter-notebookparams
      - jupyter-server-proxy
      - datalad-next
      - datalad-osf
      - datalad-ebrains
      - nilearn
      - siibra
